import Head from 'next/head'
import { NextPageWithLayout } from '../_app'
import { SiteLayout } from '@/components/Layout'

const ContactUsPage: NextPageWithLayout = () => {
	return (
		<>
			<Head>
				<title>Contact Us - HypeGenius</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/hype-genius-logo.png" />
			</Head>
			<SiteLayout>
				<main></main>
			</SiteLayout>
		</>
	)
}

export default ContactUsPage
