import { AuthLayout } from '@/components/Layout'
import { Response, api } from '@/core/axios'
import { ChannelSignup } from '@/modules/auth'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'

const title = (name: string) => (
	<>
		Join <span className="text-[#EF539E]">{name}&apos;s</span> Partner Program!
	</>
)

const SignupChannel: NextPage<{ token: string; business: string }> = ({
	token,
	business,
}) => {
	return (
		<>
			<Head>
				<title>Hype Genius - Channel Signup</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={'/hype-genius-logo.png'} />
			</Head>
			<AuthLayout
				title={title(business)}
				subTitle={`Fill out the information below :)`}
			>
				<ChannelSignup token={token} />
			</AuthLayout>
		</>
	)
}

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
	const token = query.token as string
	if (!token)
		return {
			redirect: { destination: '/', permanent: true },
		}
	try {
		const result = await api.get<Response<{ name: string }>>(
			`/auth/channel/${token}/verify`,
		)
		const data = result.data
		if (result.status !== 200) {
			throw new Error('Invalid Token')
		}
		return {
			props: { token, business: data.data.name },
		}
	} catch (error) {
		return {
			redirect: { destination: '/', permanent: true },
		}
	}
}

export default SignupChannel
