import DashboardLayout from "@/components/DashboardLayout";
import type { NextPage } from "next";
import Head from "next/head";

const ReportPage: NextPage = () => {
	return (
		<>
			<Head>
				<title>Hype Genius - Reports</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={"/hype-genius-logo.png"} />
			</Head>

			<DashboardLayout>
				<div></div>
			</DashboardLayout>
		</>
	);
};

export default ReportPage;
