import { DashboardLayout } from '@/components/Layout'
import Loading from '@/components/Loading'
import { ReportsHeader, ReportsTable } from '@/modules/reports'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Suspense } from 'react'

const ReportPage: NextPage = () => {
	return (
		<>
			<Head>
				<title>Hype Genius - Reports</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={'/hype-genius-logo.png'} />
			</Head>

			<DashboardLayout>
				<Suspense fallback={<Loading />}>
					<div className="flex flex-col w-full overflow-hidden my-[20px] mx-[10px] gap-4">
						<ReportsHeader />
						<ReportsTable />
					</div>
				</Suspense>
			</DashboardLayout>
		</>
	)
}

export default ReportPage
