import { DashboardLayout } from "@/components/Layout";
import { ReportsHeader, ReportsTable } from "@/modules/reports";
import type { NextPage } from "next";
import Head from "next/head";

const ReportPage: NextPage = () => {
	return (
		<>
			<Head>
				<title>Hype Genius - Reports</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={"/hype-genius-logo.png"} />
			</Head>

			<DashboardLayout>
				<div className="flex flex-col w-full overflow-hidden my-[20px] mx-[10px] w-full gap-4">
					<ReportsHeader />
					<ReportsTable />
				</div>
			</DashboardLayout>
		</>
	);
};

export default ReportPage;
