import { AuthLayout } from "@/components/Layout";
import { ChannelSignup } from "@/modules/auth";
import type { NextPage } from "next";
import Head from "next/head";

const title = (
	<>
		Join <span className="text-[#EF539E]">TraderEdge&apos;s</span> Partner
		Program!
	</>
);

const SignupChanel: NextPage = () => {
	return (
		<>
			<Head>
				<title>Hype Genius - Channel Signup</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={"/hype-genius-logo.png"} />
			</Head>
			<AuthLayout title={title} subTitle={`Fill out the information below :)`}>
				<ChannelSignup />
			</AuthLayout>
		</>
	);
};

export default SignupChanel;
