import { Layout } from "@/modules/auth";
import ChannelSignup from "@/modules/auth/components/ChannelSignup";
import type { NextPage } from "next";
import Head from "next/head";

const SignupChanel: NextPage = () => {
	return (
		<>
			<Head>
				<title>Hype Genius - Channel Signup</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={"/hype-genius-logo.png"} />
			</Head>
			<Layout
				title={
					<>
						Join <span className="text-[#EF539E]">TraderEdge&apos;s</span>{" "}
						Partner Program!
					</>
				}
				subTitle="Fill out the information below :)"
			>
				<ChannelSignup />
			</Layout>
		</>
	);
};

export default SignupChanel;
