import { Layout } from "@/modules/auth";
import BusinessSignup from "@/modules/auth/components/BusinessSignup";
import type { NextPage } from "next";
import Head from "next/head";

const SignupBusiness: NextPage = () => {
	return (
		<>
			<Head>
				<title>Hype Genius - Signup</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={"/hype-genius-logo.png"} />
			</Head>

			<Layout
				title="Hey! Let's get started"
				subTitle="Fill out the information below :)"
			>
				<BusinessSignup />
			</Layout>
		</>
	);
};

export default SignupBusiness;
