import type { NextPage } from "next";
import Head from "next/head";
import Logo from '@/assets/logos/hype-genius-logo.png'
import DashboardLayout from "@/components/DashboardLayout";

const DashboardPage: NextPage = () => {
	return (
		<>
			<Head>
        <title>Hype Genius - Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={"/hype-genius-logo.png"} />
      </Head>

      <DashboardLayout>
        <div></div>
      </DashboardLayout>
		</>
	);
};

export default DashboardPage;
