import type { NextPage } from "next";
import Head from "next/head";
import { DashboardLayout } from "@/components/Layout";
import EditInfluencerModal from "@/modules/modal/EditInfluencerModal";

const DashboardPage: NextPage = () => {
	return (
		<>
			<Head>
				<title>Hype Genius - Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={"/hype-genius-logo.png"} />
			</Head>

			{/* <DashboardLayout></DashboardLayout> */}
			{/* For Checking Purpose */}
			<EditInfluencerModal/>
		</>
	);
};

export default DashboardPage;
