import React, { Suspense } from 'react'
import logo from "@/assets/logos/hype-genius-logo-with-text.png"
import businessmanlogo from "@/assets/icons/businessman.png"
import startuplogo from "@/assets/icons/start-up.png"
import vector from "@/assets/icons/vector.png"
import { AiOutlineArrowRight } from "react-icons/ai"
import Image from 'next/image'
import { useQuery } from 'react-query'
import { QUERY_KEYS } from '@/core/constants'
import { GetServerSideProps, NextPage } from 'next'
import { AuthApi } from '@/api/AuthApi'
import InfluencerOnboarding from '@/modules/auth/components/InfluencerOnboarding'
import Loading from '@/components/Loading'
import Head from 'next/head'

const OnboardingPage: NextPage<{ token: string }> = ({ token }) => {
	return (
		<>
			<Head>
				<title>Hype Genius - Influencer Onboarding</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={"/hype-genius-logo.png"} />
			</Head>
			<Suspense fallback={<Loading />}>
				<InfluencerOnboarding token={token} />
			</Suspense>
		</>
	)
}

export const getServerSideProps: GetServerSideProps = async ({
	req,
	query,
}) => {
	const token = query.token as string;
	if (!token)
		return {
			redirect: { destination: "/", permanent: true },
		};
	return {
		props: { token },
	};
};

export default OnboardingPage
