import type { NextPage } from "next";
import Head from "next/head";
import Logo from '@/assets/logos/hype-genius-logo.png'

const DashboardPage: NextPage = () => {
	return (
		<>
			<Head>
        <title>Hype Genius - Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={"/hype-genius-logo.png"} />
      </Head>
			<div>
				
			</div>
		</>
	);
};

export default DashboardPage;
