import Subscription_Billing from "@/modules/settings/components/Subscription_Billing";
import type { NextPage } from "next";
import { DashboardLayout } from "@/components/Layout";
import Head from "next/head";
const Billing_Subscription:NextPage=()=>{
    return(

        <>
        <Head>
          <title>Hype Genius - Subscription-Billing</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href={"/hype-genius-logo.png"} />
        </Head>
        <DashboardLayout>
            <Subscription_Billing/>
        </DashboardLayout>
        </>
    )
}
export default Billing_Subscription;