import React from "react";
import { DashboardLayout } from "@/components/Layout";
import type { NextPage } from "next";
import Head from "next/head";
import {
	SettingsOnboarding,
	CustomerSettings,
	BillingsSettings,
} from "@/modules/settings";
import AccountSettings from "@/modules/settings/components/AccountSettings";
const SettingsPage: NextPage = () => {

	return (
		<>
			<Head>
				<title>Hype Genius - Settings</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={"/hype-genius-logo.png"} />
			</Head>

			<DashboardLayout>
				<div className="grid mt-3 grid-cols-[1.5fr_1fr_1fr] grid-rows-[170px_280px_170px] gap-5 w-full grid-flow-col-dense">
					<CustomerSettings />
					<AccountSettings />
					<BillingsSettings />
					<SettingsOnboarding />
				</div>
			</DashboardLayout>
		</>
	);
};
export default SettingsPage;
