import React, { Suspense } from 'react'
import { DashboardLayout } from '@/components/Layout'
import type { NextPage } from 'next'
import Head from 'next/head'
import {
	SettingsOnboarding,
	CustomerSettings,
	BillingsSettings,
	Logout,
} from '@/modules/settings'
import AccountSettings from '@/modules/settings/components/AccountSettings'
import Loading from '@/components/Loading'
import { useUser } from '@/modules/auth/hooks/useUser'
const SettingsPage: NextPage = () => {
	const { data: user } = useUser({})

	return (
		<>
			<Head>
				<title>Hype Genius - Settings</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={'/hype-genius-logo.png'} />
			</Head>

			<DashboardLayout>
				<Suspense fallback={<Loading />}>
					<div className="grid mt-3 grid-cols-[1.5fr_1fr_1fr] gap-5 w-full">
						<div className="flex flex-col gap-5">
							{user?.data.user.role === 'business_admin' && (
								<CustomerSettings />
							)}
							<AccountSettings />
							<BillingsSettings />
							<Logout />
						</div>
						{user?.data.user.role === 'business_admin' && (
							<div>
								<SettingsOnboarding />
							</div>
						)}
					</div>
				</Suspense>
			</DashboardLayout>
		</>
	)
}
export default SettingsPage
