import {
	InvoiceHistory,
	PaymentMethod,
	SubscriptionBilling,
} from "@/modules/settings";
import type { NextPage } from "next";
import { DashboardLayout } from "@/components/Layout";
import Head from "next/head";
import { useRouter } from "next/router";
const SubscriptionPage: NextPage = () => {
	const router = useRouter();
	return (
		<>
			<Head>
				<title>Hype Genius - Subscription-Billing</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={"/hype-genius-logo.png"} />
			</Head>
			<DashboardLayout>
				<div className="flex flex-col max-w-220px mt-[20px] space-y-5">
					<button
						onClick={() => router.back()}
						className="bg-[#D7D7D7] w-[60px] py-1  rounded-xl"
					>
						Back
					</button>
					<SubscriptionBilling />
					<PaymentMethod />
					<InvoiceHistory />
				</div>
			</DashboardLayout>
		</>
	);
};
export default SubscriptionPage;
