
import {Header,Content,HowItWorks,Footer} from "@/modules/home"
import {Login,Signin} from "@/modules/auth"
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
			<title>HypeGenius</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="w-screen">
				<Header/>
				 <Content/>
				<HowItWorks/>
				<Footer/> 
				
				
       
      </main>
	 
		</>
	);
}
