import AuthRoutes from "@/components/Routes/AuthRoutes";
import { Header, Content, HowItWorks, Footer } from "@/modules/home";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Home - HypeGenius</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/hype-genius-logo.png" />
			</Head>
			<main className="w-full overflow-x-hidden max-w-screen">
				<AuthRoutes>
					<Header />
					<Content />
					<HowItWorks />
					<Footer />
				</AuthRoutes>
			</main>
		</>
	);
}
