export const QUERY_KEYS = {
	GET_VIDEOS: 'videos/get',
	UPLOAD_VIDEO: 'video/upload',
	ADD_NOTE: 'note/add',
	GET_NOTES: 'note/get',
	GET_INFLUENCERS: 'influencers/get',
	CREATE_ONBOARING: 'onboarding/create',
	UPDATE_ONBOARDING: 'onboarding/update',
	GET_MY_BUSINESS: 'my-business/get',
	UPDATE_BUSINESS: 'business/update',
	GET_CURRENCY_LIST: 'currency/get',
	ADD_ACTIVITY: 'activity/add',
	GET_ACTIVITIES: 'activity/get',
	GET_ALERTS: 'alerts/get',
	CREATE_CONTRACT: 'contract/create',
	UPDATE_CONTRACT: 'contract/update',
	CREATE_PAYMENT: 'payment/create',
	GET_REPORT: 'report/get',
	BUSINESS_ANALYTICS: 'business/analytics',
	CHANNEL_ANALYTICS: 'channel/analytics',
	GET_INFLUENCER_ONBOARDINGS: 'influencer-onboardings/get',
	UPDATE_USER: 'user/update',
	GET_METRICS: 'metrics/get',
	GET_TAGS: 'tags/get',
	CREATE_FOLLOWUP: 'followup/create',
}

export const MONTHS = [
	'Jan',
	'Feb',
	'March',
	'April',
	'June',
	'July',
	'Aug',
	'Sept',
	'Oct',
	'Nov',
	'Dec',
]

export const CONTRACT_KEY = '@contractTemp'
