import type { NextPage } from "next";
import { DashboardLayout } from "@/components/Layout";
import Head from "next/head";
import { InfluencersDetail, InfluencersTable } from "@/modules/influencers";
import { useState } from "react";

const InfluencerPage: NextPage = () => {
	const [selectedInfluencer, setSelectedInfluencer] = useState<number | null>(
		1
	);

	return (
		<>
			<Head>
				<title>Hype Genius - Influencers</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={"/hype-genius-logo.png"} />
			</Head>

			<DashboardLayout>
				<div className="grid w-full grid-cols-8 gap-3">
					<InfluencersTable
						selectedInfluencer={selectedInfluencer}
						setSelectedInfluencer={setSelectedInfluencer}
					/>
					{selectedInfluencer !== null ? (
						<InfluencersDetail
							selectedInfluencer={selectedInfluencer}
							setSelectedInfluencer={setSelectedInfluencer}
						/>
					) : null}
				</div>
			</DashboardLayout>
		</>
	);
};

export default InfluencerPage;
