import type { NextPage } from "next";
import { DashboardLayout } from "@/components/Layout";
import Head from "next/head";
import { InfluencerContainer, InfluencersDetail } from "@/modules/influencers";
import { AppState } from "@/store";
import { useSelector } from "react-redux";
import { PanelType } from "@/modules/influencers/core/types";
import Payment from "@/modules/influencers/components/Payment";

const panels: Record<PanelType, React.ReactNode> = {
	detail: <InfluencersDetail />,
	payment: <Payment />
}

const InfluencerPage: NextPage = () => {
	const isInfluencerSelected = useSelector<AppState, boolean>(state => state.influencers.influencer !== null);
	const panel = useSelector((state: AppState) => state.influencers.panel)

	return (
		<>
			<Head>
				<title>Hype Genius - Influencers</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={"/hype-genius-logo.png"} />
			</Head>

			<DashboardLayout>
				<div className="grid w-full grid-cols-8 gap-3">
					<InfluencerContainer />
					{isInfluencerSelected && panel ?
						panels[panel]
						: null}
				</div>
			</DashboardLayout>
		</>
	);
};

export default InfluencerPage;
